[package]
name = "nvi-win"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
futures-util = "0.3.31"
nvi = { path = "../nvi/crates/nvi" }
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = ["full"] }
tracing = "0.1.41"

